version: '3.8'

services:
  traefik:
    image: traefik:v2.10
    command:
      - '--api.insecure=true' # Dashboard
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--entrypoints.web.address=:80'
      - '--entrypoints.websecure.address=:443'
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080' # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik-public

  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.api.rule=Host(`api.localhost`)'
      - 'traefik.http.services.api.loadbalancer.server.port=3000'
      - 'traefik.http.routers.api.entrypoints=web'
    networks:
      - traefik-public
    restart: unless-stopped

networks:
  traefik-public:
    name: traefik-public
